---


# Run these first
# Otherwise packages will fail to download
- name: Get best mirrors
  include_tasks: reflector.yaml
  when:
    - packages__reflector

- name: Set GPG config
  include_tasks: gpg.yaml

# This needs to run after reflector
- name: Configure pacman
  include_tasks: pacman_conf.yaml

- name: Install AUR helper
  include_tasks: aur_helper.yaml

- name: Install packages
  include_tasks: packages.yaml
