---

- name: Install lspci
  pacman:
    name: pciutils
    state: present

- name: Look for GPUs on PCIe bus
  shell: "set -o pipefail; lspci -v -s $(lspci | grep ' VGA ' | cut -d' ' -f 1)"
  register: gpus_lspci
  changed_when: no

- name: Check which GPUs are present
  set_fact:
    gpu: >-
      {{
        ('amd' if 'AMD' in gpus_lspci.stdout
        else 'intel' if 'Intel' in gpus_lspci.stdout
        else 'nvidia' if 'NVIDIA' in gpus_lspci.stdout) | default('generic')
      }}

- name: Install GPU drivers
  pacman:
    name: "{{ lookup('vars', 'packages__gpu_' + gpu) }}"
    state: present

- name: Install Xorg
  pacman:
    name: "{{ packages__xorg }}"
    state: present

- name: Install packages
  aur:
    name: "{{ packages__pkgs }}"
    state: present
  become: yes
  become_user: aurbuilder

# This is horribly hacky, but --noconfirm auto-fails
- name: Install pipewire
  # yamllint disable-line rule:command-instead-of-shell
  shell: "set -o pipefail; yes | pacman -S {{ packages__pipewire | join(' ') }}"
  register: pipewire
  changed_when: "{{ ' installing' in pipewire.stdout }}"
