---

- name: Set pacman config
  template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  become_user: root

- name: Pull in multilib
  pacman:
    update_cache: yes
    upgrade: yes
